CREATE TABLE [dbo].[IMPORT_CONFIGURATION] (
    [DATA_FEED]      VARCHAR (16)  NULL,
    [IMPORT_CLASS]   VARCHAR (128) NULL,
    [CLASS_ARCHIVE]  VARCHAR (128) NULL,
    [IMPORT_UTILITY] VARCHAR (128) NULL,
    [PARAMETERS1]    VARCHAR (128) NULL,
    [PARAMETERS2]    VARCHAR (128) NULL,
    [PROCESSING_DIR] VARCHAR (128) NULL
);

