//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LatitudeLongitude", Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    [System.SerializableAttribute()]
    public partial class LatitudeLongitude : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OSGridReference", Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    [System.SerializableAttribute()]
    public partial class OSGridReference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EastingField;
        
        private int NorthingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Easting {
            get {
                return this.EastingField;
            }
            set {
                if ((this.EastingField.Equals(value) != true)) {
                    this.EastingField = value;
                    this.RaisePropertyChanged("Easting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Northing {
            get {
                return this.NorthingField;
            }
            set {
                if ((this.NorthingField.Equals(value) != true)) {
                    this.NorthingField = value;
                    this.RaisePropertyChanged("Northing");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sjp.london2012.com/CoordinateConvertorService", ConfigurationName="CoordinateConvertorWebService.CoordinateConvertorSoap")]
    public interface CoordinateConvertorSoap {
        
        // CODEGEN: Generating message contract since element name latlongs from namespace http://sjp.london2012.com/CoordinateConvertorService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sjp.london2012.com/CoordinateConvertorService/ConvertLatitudeLongitudetoOS" +
            "GR", ReplyAction="*")]
        SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRResponse ConvertLatitudeLongitudetoOSGR(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRRequest request);
        
        // CODEGEN: Generating message contract since element name osgrs from namespace http://sjp.london2012.com/CoordinateConvertorService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sjp.london2012.com/CoordinateConvertorService/ConvertOSGRtoLatitudeLongitu" +
            "de", ReplyAction="*")]
        SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeResponse ConvertOSGRtoLatitudeLongitude(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sjp.london2012.com/CoordinateConvertorService/TestActive", ReplyAction="*")]
        bool TestActive();
        
        // CODEGEN: Generating message contract since element name TestConvertOSGRToLatitudeLongitudeResult from namespace http://sjp.london2012.com/CoordinateConvertorService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sjp.london2012.com/CoordinateConvertorService/TestConvertOSGRToLatitudeLon" +
            "gitude", ReplyAction="*")]
        SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeResponse TestConvertOSGRToLatitudeLongitude(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertLatitudeLongitudetoOSGRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertLatitudeLongitudetoOSGR", Namespace="http://sjp.london2012.com/CoordinateConvertorService", Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRRequestBody Body;
        
        public ConvertLatitudeLongitudetoOSGRRequest() {
        }
        
        public ConvertLatitudeLongitudetoOSGRRequest(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    public partial class ConvertLatitudeLongitudetoOSGRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude[] latlongs;
        
        public ConvertLatitudeLongitudetoOSGRRequestBody() {
        }
        
        public ConvertLatitudeLongitudetoOSGRRequestBody(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude[] latlongs) {
            this.latlongs = latlongs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertLatitudeLongitudetoOSGRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertLatitudeLongitudetoOSGRResponse", Namespace="http://sjp.london2012.com/CoordinateConvertorService", Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRResponseBody Body;
        
        public ConvertLatitudeLongitudetoOSGRResponse() {
        }
        
        public ConvertLatitudeLongitudetoOSGRResponse(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    public partial class ConvertLatitudeLongitudetoOSGRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.OSGridReference[] ConvertLatitudeLongitudetoOSGRResult;
        
        public ConvertLatitudeLongitudetoOSGRResponseBody() {
        }
        
        public ConvertLatitudeLongitudetoOSGRResponseBody(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.OSGridReference[] ConvertLatitudeLongitudetoOSGRResult) {
            this.ConvertLatitudeLongitudetoOSGRResult = ConvertLatitudeLongitudetoOSGRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertOSGRtoLatitudeLongitudeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertOSGRtoLatitudeLongitude", Namespace="http://sjp.london2012.com/CoordinateConvertorService", Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeRequestBody Body;
        
        public ConvertOSGRtoLatitudeLongitudeRequest() {
        }
        
        public ConvertOSGRtoLatitudeLongitudeRequest(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    public partial class ConvertOSGRtoLatitudeLongitudeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.OSGridReference[] osgrs;
        
        public ConvertOSGRtoLatitudeLongitudeRequestBody() {
        }
        
        public ConvertOSGRtoLatitudeLongitudeRequestBody(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.OSGridReference[] osgrs) {
            this.osgrs = osgrs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertOSGRtoLatitudeLongitudeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertOSGRtoLatitudeLongitudeResponse", Namespace="http://sjp.london2012.com/CoordinateConvertorService", Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeResponseBody Body;
        
        public ConvertOSGRtoLatitudeLongitudeResponse() {
        }
        
        public ConvertOSGRtoLatitudeLongitudeResponse(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    public partial class ConvertOSGRtoLatitudeLongitudeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude[] ConvertOSGRtoLatitudeLongitudeResult;
        
        public ConvertOSGRtoLatitudeLongitudeResponseBody() {
        }
        
        public ConvertOSGRtoLatitudeLongitudeResponseBody(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude[] ConvertOSGRtoLatitudeLongitudeResult) {
            this.ConvertOSGRtoLatitudeLongitudeResult = ConvertOSGRtoLatitudeLongitudeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConvertOSGRToLatitudeLongitudeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConvertOSGRToLatitudeLongitude", Namespace="http://sjp.london2012.com/CoordinateConvertorService", Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeRequestBody Body;
        
        public TestConvertOSGRToLatitudeLongitudeRequest() {
        }
        
        public TestConvertOSGRToLatitudeLongitudeRequest(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    public partial class TestConvertOSGRToLatitudeLongitudeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int easting;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int northing;
        
        public TestConvertOSGRToLatitudeLongitudeRequestBody() {
        }
        
        public TestConvertOSGRToLatitudeLongitudeRequestBody(int easting, int northing) {
            this.easting = easting;
            this.northing = northing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConvertOSGRToLatitudeLongitudeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConvertOSGRToLatitudeLongitudeResponse", Namespace="http://sjp.london2012.com/CoordinateConvertorService", Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeResponseBody Body;
        
        public TestConvertOSGRToLatitudeLongitudeResponse() {
        }
        
        public TestConvertOSGRToLatitudeLongitudeResponse(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sjp.london2012.com/CoordinateConvertorService")]
    public partial class TestConvertOSGRToLatitudeLongitudeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude TestConvertOSGRToLatitudeLongitudeResult;
        
        public TestConvertOSGRToLatitudeLongitudeResponseBody() {
        }
        
        public TestConvertOSGRToLatitudeLongitudeResponseBody(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude TestConvertOSGRToLatitudeLongitudeResult) {
            this.TestConvertOSGRToLatitudeLongitudeResult = TestConvertOSGRToLatitudeLongitudeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoordinateConvertorSoapChannel : SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoordinateConvertorSoapClient : System.ServiceModel.ClientBase<SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap>, SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap {
        
        public CoordinateConvertorSoapClient() {
        }
        
        public CoordinateConvertorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoordinateConvertorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinateConvertorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinateConvertorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRResponse SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap.ConvertLatitudeLongitudetoOSGR(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRRequest request) {
            return base.Channel.ConvertLatitudeLongitudetoOSGR(request);
        }
        
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.OSGridReference[] ConvertLatitudeLongitudetoOSGR(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude[] latlongs) {
            SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRRequest inValue = new SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRRequest();
            inValue.Body = new SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRRequestBody();
            inValue.Body.latlongs = latlongs;
            SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertLatitudeLongitudetoOSGRResponse retVal = ((SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap)(this)).ConvertLatitudeLongitudetoOSGR(inValue);
            return retVal.Body.ConvertLatitudeLongitudetoOSGRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeResponse SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap.ConvertOSGRtoLatitudeLongitude(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeRequest request) {
            return base.Channel.ConvertOSGRtoLatitudeLongitude(request);
        }
        
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude[] ConvertOSGRtoLatitudeLongitude(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.OSGridReference[] osgrs) {
            SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeRequest inValue = new SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeRequest();
            inValue.Body = new SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeRequestBody();
            inValue.Body.osgrs = osgrs;
            SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.ConvertOSGRtoLatitudeLongitudeResponse retVal = ((SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap)(this)).ConvertOSGRtoLatitudeLongitude(inValue);
            return retVal.Body.ConvertOSGRtoLatitudeLongitudeResult;
        }
        
        public bool TestActive() {
            return base.Channel.TestActive();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeResponse SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap.TestConvertOSGRToLatitudeLongitude(SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeRequest request) {
            return base.Channel.TestConvertOSGRToLatitudeLongitude(request);
        }
        
        public SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.LatitudeLongitude TestConvertOSGRToLatitudeLongitude(int easting, int northing) {
            SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeRequest inValue = new SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeRequest();
            inValue.Body = new SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeRequestBody();
            inValue.Body.easting = easting;
            inValue.Body.northing = northing;
            SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.TestConvertOSGRToLatitudeLongitudeResponse retVal = ((SJP.UserPortal.CoordinateConvertorProvider.CoordinateConvertorWebService.CoordinateConvertorSoap)(this)).TestConvertOSGRToLatitudeLongitude(inValue);
            return retVal.Body.TestConvertOSGRToLatitudeLongitudeResult;
        }
    }
}
