ALTER TABLE [dbo].[SJPVenueGates]
	ADD CONSTRAINT [PK_SJPVenueGates]
    PRIMARY KEY CLUSTERED ([EntranceNaPTAN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
