ALTER TABLE [dbo].[Interchange]
    ADD CONSTRAINT [IX_Interchange_DuplicateChecking] UNIQUE NONCLUSTERED ([FromNodeID] ASC, [FromNodeTypeID] ASC, [ToNodeID] ASC, [ToNodeTypeID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];



