ALTER TABLE [dbo].[properties]
    ADD CONSTRAINT [PK_PropertieswithPartnerId] PRIMARY KEY CLUSTERED ([pName] ASC, [AID] ASC, [GID] ASC, [PartnerId] ASC, [ThemeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

