ALTER TABLE [dbo].[Partner]
    ADD CONSTRAINT [PK_Partner] PRIMARY KEY CLUSTERED ([PartnerId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

