//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJP.UserPortal.SJPWeb.Controls {
    
    
    public partial class HeaderControl {
        
        /// <summary>
        /// pnlHeaderMastheadContainerEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderMastheadContainerEn;
        
        /// <summary>
        /// liSkipToContentLinkEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liSkipToContentLinkEn;
        
        /// <summary>
        /// skipToLinkControlEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.SkipToLinkControl skipToLinkControlEn;
        
        /// <summary>
        /// liCookiesLinkEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCookiesLinkEn;
        
        /// <summary>
        /// liLanguageLinkEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLanguageLinkEn;
        
        /// <summary>
        /// languageLinkControlEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.LanguageLinkControl languageLinkControlEn;
        
        /// <summary>
        /// pnlHeaderMastheadContainerEnPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderMastheadContainerEnPara;
        
        /// <summary>
        /// liSkipToContentLinkEnPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liSkipToContentLinkEnPara;
        
        /// <summary>
        /// skipToLinkControlEnPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.SkipToLinkControl skipToLinkControlEnPara;
        
        /// <summary>
        /// liCookiesLinkEnPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCookiesLinkEnPara;
        
        /// <summary>
        /// liLanguageLinkEnPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLanguageLinkEnPara;
        
        /// <summary>
        /// languageLinkControlEnPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.LanguageLinkControl languageLinkControlEnPara;
        
        /// <summary>
        /// pnlHeaderMastheadContainerFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderMastheadContainerFr;
        
        /// <summary>
        /// liSkipToContentLinkFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liSkipToContentLinkFr;
        
        /// <summary>
        /// skipToLinkControlFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.SkipToLinkControl skipToLinkControlFr;
        
        /// <summary>
        /// liCookiesLinkFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCookiesLinkFr;
        
        /// <summary>
        /// liLanguageLinkFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLanguageLinkFr;
        
        /// <summary>
        /// languageLinkControlFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.LanguageLinkControl languageLinkControlFr;
        
        /// <summary>
        /// pnlHeaderMastheadContainerFrPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderMastheadContainerFrPara;
        
        /// <summary>
        /// liSkipToContentLinkFrPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liSkipToContentLinkFrPara;
        
        /// <summary>
        /// skipToLinkControlFrPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.SkipToLinkControl skipToLinkControlFrPara;
        
        /// <summary>
        /// liCookiesLinkFrPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liCookiesLinkFrPara;
        
        /// <summary>
        /// liLanguageLinkFrPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liLanguageLinkFrPara;
        
        /// <summary>
        /// languageLinkControlFrPara control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.LanguageLinkControl languageLinkControlFrPara;
        
        /// <summary>
        /// pnlHeaderPrimaryContainerEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderPrimaryContainerEn;
        
        /// <summary>
        /// pnlHeaderPrimaryContainerFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderPrimaryContainerFr;
        
        /// <summary>
        /// pnlHeaderSecondaryContainerEn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderSecondaryContainerEn;
        
        /// <summary>
        /// pnlHeaderSecondaryContainerFr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlHeaderSecondaryContainerFr;
    }
}
