//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJP.UserPortal.SJPWeb.Controls {
    
    
    public partial class SideBarRightControl {
        
        /// <summary>
        /// topTipsWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.TopTipsWidget topTipsWidget;
        
        /// <summary>
        /// faqWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.GenericPromoWidget faqWidget;
        
        /// <summary>
        /// journeyPlannerWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.JourneyPlannerWidget journeyPlannerWidget;
        
        /// <summary>
        /// venueMapsWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.VenueMapsWidget venueMapsWidget;
        
        /// <summary>
        /// travelNewsWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.TravelNewsWidget travelNewsWidget;
        
        /// <summary>
        /// walkingWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.GenericPromoWidget walkingWidget;
        
        /// <summary>
        /// gamesTravelCardWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.GenericPromoWidget gamesTravelCardWidget;
        
        /// <summary>
        /// accessibleTravelWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.GenericPromoWidget accessibleTravelWidget;
        
        /// <summary>
        /// gbGNATMapWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.GNATMapsWidget gbGNATMapWidget;
        
        /// <summary>
        /// seGNATMapWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.GNATMapsWidget seGNATMapWidget;
        
        /// <summary>
        /// londonGNATMapWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.GNATMapsWidget londonGNATMapWidget;
        
        /// <summary>
        /// travelNewsInfoWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SJP.UserPortal.SJPWeb.Controls.TravelNewsInfoWidget travelNewsInfoWidget;
    }
}
